kind: Service
apiVersion: v1
metadata:
  name: croplands-tiles
  namespace: croplands
spec:
  selector:
    app: croplands-tiles
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8000

